import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/_components/NavBar";
import MaxWidthWrapper from "@/app/_components/MaxWithWrapper";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "./_components/ThemeProvider";
import Footer from "./_components/Footer";

const lora = Lora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lora.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MaxWidthWrapper>
            <NavBar />
            {children}
            <Toaster />
            <Footer />
          </MaxWidthWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
