import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/_components/NavBar";
import MaxWidthWrapper from "@/app/_components/MaxWithWrapper";
import Footer from "@/app/_components/Footer";
import { Toaster } from "@/components/ui/toaster";

const lora = Lora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lora.className}`}>
        <MaxWidthWrapper>
          <NavBar />
          {children}
          <Footer />
          <Toaster />
        </MaxWidthWrapper>
      </body>
    </html>
  );
}
